import sqlalchemy as db
engine=db.create_engine('sqlite:///movies.db')
connection=engine.connect()
metadata=db.MetaData()
movies=db.Table('Movies',metadata,autoload=True,autoload_with=engine)
query=db.select([movies])
result_proxy=connection.execute(query)
result_set=result_proxy.fetchall()
print(result_set[0:])
query=movies.select(movies.columns.year>2000)
result_proxy=connection.execute(query)
result_set=result_proxy.fetchall()
print(result_set)
query=movies.select().where(movies.columns.director=="Wes Anderson")
result_proxy=connection.execute(query)
result_set=result_proxy.fetchall()
print(result_set)

